name: base

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/base.yaml'
      - 'docker/base/**'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/base.yaml'
      - 'docker/base/**'
    tags:
      - 'base-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      -
        name: Docker Build
        run: |
          docker build \
            --tag "crazymax/xgo:base" \
            --file ./docker/base/Dockerfile ./docker/base
      -
        name: Login to DockerHub
        if: success() && startsWith(github.ref, 'refs/tags/base-')
        uses: crazy-max/ghaction-docker-login@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Push
        if: success() && startsWith(github.ref, 'refs/tags/base-')
        run: |
          docker push crazymax/xgo
