name: go-1.13

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/go-1.13.yaml'
      - 'docker/go-1.13/**'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/go-1.13.yaml'
      - 'docker/go-1.13/**'
    tags:
      - 'go-1.13-*'

jobs:
  docker:
    strategy:
      matrix:
        go_version:
          - 1.13.0
          - 1.13.1
          - 1.13.2
          - 1.13.3
          - 1.13.4
          - 1.13.5
          - 1.13.6
          - 1.13.7
          - 1.13.8
          - 1.13.9
          - 1.13.10
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Get Latest
        run: |
          echo "##[set-env name=LATEST;]$(cat docker/go-1.13/latest)"
      -
        name: Docker Build
        run: |
          docker build \
            --tag "crazymax/xgo:${{ matrix.go_version }}" \
            --file ./docker/go-1.13/go-${{ matrix.go_version }}/Dockerfile \
            ./docker/go-1.13/go-${{ matrix.go_version }}
          if [ "$LATEST" == "${{ matrix.go_version }}" ]; then
            docker tag "crazymax/xgo:${{ matrix.go_version }}" "crazymax/xgo:1.13.x"
          fi
      -
        name: Docker Login
        if: success() && startsWith(github.ref, 'refs/tags/go-1.13-')
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username crazymax --password-stdin
      -
        name: Docker Push
        if: success() && startsWith(github.ref, 'refs/tags/go-1.13-')
        run: |
          docker image rm crazymax/xgo:base
          docker push crazymax/xgo
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
