name: go-1.15

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/go-1.15.yaml'
      - 'docker/go-1.15/**'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/go-1.15.yaml'
      - 'docker/go-1.15/**'
    tags:
      - 'go-1.15-*'

jobs:
  docker:
    strategy:
      matrix:
        go_version:
          - 1.15.0
          - 1.15.1
          - 1.15.2
          - 1.15.3
          - 1.15.4
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get Latest
        run: |
          echo "##[set-env name=LATEST;]$(cat docker/go-1.15/latest)"
      -
        name: Docker Build
        run: |
          docker build \
            --tag "crazymax/xgo:${{ matrix.go_version }}" \
            --tag "ghcr.io/crazy-max/xgo:${{ matrix.go_version }}" \
            --file ./docker/go-1.15/go-${{ matrix.go_version }}/Dockerfile \
            ./docker/go-1.15/go-${{ matrix.go_version }}
          if [ "$LATEST" == "${{ matrix.go_version }}" ]; then
            docker tag "crazymax/xgo:${{ matrix.go_version }}" "crazymax/xgo:1.15.x"
            docker tag "crazymax/xgo:${{ matrix.go_version }}" "crazymax/xgo:latest"
          fi
      -
        name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/go-1.15-')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        if: startsWith(github.ref, 'refs/tags/go-1.15-')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Docker Push
        if: startsWith(github.ref, 'refs/tags/go-1.15-')
        run: |
          docker image rm crazymax/xgo:base
          docker push crazymax/xgo
          docker push ghcr.io/crazy-max/xgo
